version: '3.8'

services:
  db:
    image: postgres
    container_name: library-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: LibraryDb
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: library-app
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LibraryDb;Username=postgres;Password=password;
    depends_on:
      - db